Add (2-norm) condition numbers to output data information.
DarkEnergyScienceCollaboration/WeakLensingDeblending pull request #42
Opened 2019-06-28 22:33 UTC by ismael2395

Hi David and Javier, 

Pat and I have been investigating some of the the more fundamental issues that led us to using the pseudo-inverse in the first place. Our conclusions for the pseudo-inverse (also from Javier's tests) seem to be that the pseudo-inverse is not a magic bullet, and there are some other problems that need to be addressed. 

More recently, we revisited this paper https://arxiv.org/abs/gr-qc/0703086 on Use and Abuse of the Fisher Matrix  and we decided to  investigate condition numbers of fisher matrices further -- since they can lead to huge losses in accuracy of fisher elements (see section IV of paper). 

Once we have investigated this a bit more, we will give you an update. For now I just wanted to propose adding the condition numbers of the fisher matrices of a group and of individual galaxies to the output table, I think it will be helpful going forward. Since the condition number gives us a sense of how ill-defined a matrix is when trying to invert it. 

Could you review my code and see if there is anything missing or incorrect? Thanks in advance!

2019-06-28 22:57 UTC, fjaviersanchez requested changes
Thanks a lot @ismael2395! The changes look good to me. I have a small request before approving. Please, document these new columns here: `https://github.com/LSSTDESC/WeakLensingDeblending/blob/master/docs/output.rst`.

2019-06-29 03:03 UTC, ismael2395 commented
@fjaviersanchez I just added the changes and documented `cond_num`, so please let me know if everything looks good thanks  and if I should go ahead with the merge. Thanks!

2019-06-29 03:21 UTC, fjaviersanchez approved these changes
Thanks!!

2019-06-29 03:22 UTC, fjaviersanchez commented
I think that you can go ahead and merge :)

2019-06-29 03:40 UTC, merged

2019-06-29 03:40 UTC, ismael2395 commented
Perfect, please @dkirkby reopen if there some issue we didn't see.