Add citation details
DarkEnergyScienceCollaboration/WeakLensingDeblending pull request #54
Opened 2021-10-01 16:28 UTC by fjaviersanchez

Adding badges and citation details to the repo.

2021-10-01 16:54 UTC, dkirkby commented
I suggest slightly stronger wording, e.g. change

> ... please consider citing ... or ...

to

> ...please cite ... and ...

2021-10-01 17:43 UTC, ismael-mendoza requested changes
Thanks @fjaviersanchez ! Just a couple of small comments.

2021-10-01 17:43 UTC, ismael-mendoza commented on CITATION.cff
> +message: "If you use this software, please cite it as below."
is this repeated by mistake?

2021-10-01 17:43 UTC, ismael-mendoza commented on README.md
> +If you use this software please cite [2021JCAP...07..043S](https://ui.adsabs.harvard.edu/abs/2021JCAP...07..043S/abstract) and [this zenodo link](https://zenodo.org/record/3975230#.YVczD2ZKjAM).
Should everyone cite the Zenodo and the JCAP ? or only people that use the code directly should cite the Zenodo?

2021-10-07 19:49 UTC, ismael-mendoza commented on README.md
> +If you use this software please cite [2021JCAP...07..043S](https://ui.adsabs.harvard.edu/abs/2021JCAP...07..043S/abstract) and [this zenodo link](https://zenodo.org/record/3975230#.YVczD2ZKjAM).
@dkirkby mentioned that people should cite both in this order so this looks good to me

2021-10-08 16:38 UTC, ismael-mendoza approved these changes
Looks good, thanks @fjaviersanchez !

2021-10-08 16:44 UTC, merged